### ISSUE TITLE
Mobilizon-instanssi

### ISSUE THREAD

**Issue by vranki** [pikaviestin/documentation#10]
Matrix-pannun kaveriksi sopisi hyvin samalle yleisölle tarkotettu Mobilizon-instanssi. Jonkinlaisella SSO-mekanismilla voisi käyttää Matrix-tunnareita siihen kirjautumiseen.

(Tämä siis jatkoideana sitten kun Matrix on pystyssä ja toimii)

**Comment by vranki** [comment]
Kaivataan virtuaali:
 - 2gb RAM
 - 20gb levyä
 - 1 cpu

DNS:n kaivataan nimi tapahtumat.pikaviestin.fi joka osoittamaan k.o virtuaaliin.
 
Autentikointi authentikia vastaan pitäisi onnistua OpenID Connectilla Keycloak-konfiguraatiolla (kertoo Mobilizon-devaaja)

Liittyviä dokkareita:

https://docs.joinmobilizon.org/administration/configure/auth/
https://goauthentik.io/docs/terminology

Assignoitu uumakselle ATK-resurssien hankintaa varten, palauta mulle kun ne on hoidettu.

**Comment by jhulkko** [comment]
Onko Mobilizonista hyötyä laajemmin, jos auth on sidottu tuohon samaan kontekstiin? Miten esim eventteihin osallistujat? Tarviiko kaikilla olla tunnus, vai vaan eventtien ylläpitäjillä? Lisäksi, onko tämä pikaviestin-konseptin scopessa varsinaisesti, vai kannattaisiko miettiä enempikin rinnakkaisena konseptina, joka voisi palvella osin myös eriä käyttäjäkuntaa?

Pohtia voisi esim sitä, että voisiko Mobilizonin tarjota samalla myös vaikkapa Kapsin jäsenistölle?

En missään nimessä ole ajatusta vastaan, vaan koitan miettiä millaiseen suuntaan kokonaisuutta olisi luontevaa rakentaa pitkäjänteisesti. Laajemmassa scopessa esimerkiksi Mastodon-instanssi voisi olla hyvin kiinnostava samalle kohdeyleisölle.

**Comment by vranki** [comment]
Osallistujat voi osallistua pelkällä sähköpostiosoitteella tai tunnuksella toisella instanssilla.

Mietin ylläpitokanavallakin, että pitäisikö olla oma domain vai ei. Alidomain on kuitenkin a) ilmainen b) helppo järjestää joten ehdottaisin että tehdään noin. Se ei myöskään rajaa pois myöhemmin perustettavaa omaa domainia.

Mobilizon on sangen kevyt palvelu, Kapsin ehkä kannattaisi pystyttää oma instanssi omaa käyttäjätietokantaansa vasten. 

Suomenkieliselle yleisölle on jo Mastodon-instanssi https://mastodontti.fi/ ja englanninkielisistä ei ole pulaa.

**Comment by samip5** [comment]
@vranki Tapahtumat instanssi on nyt olemassa.

**Comment by vranki** [comment]
Mobilizon asennettu ja ehkä konffattu authentikiä vasten. Ilmeisesti proxy ei ole vielä konffattu enkä saanut selville missä se pyörii joten säätö jäi siihen. 

"You'll need your own reverse-proxy to handle TLS termination (on port 4000)."

**Comment by vranki** [comment]
Nyt vaikuttaisi olevan login toiminnassa. Vaatii vielä kustomointia, mutta aletaan olemaan maalisuoralla. Päivitykset ja backupt pitää myös selvittää.

**Comment by samip5** [comment]
Hmm, tää varmaan pitäisi siirtää kontti koneelle? Mietteitä? @vranki

**Comment by vranki** [comment]
Siirretty konttikoneelle ja admin-työkalut toimii nyt SSO:lla. https://järkkää.fi/ on nyt käytössä.
